"""Add auto_rip to drives

Revision ID: d4d4b49b2b88
Revises: e2d213de7806
Create Date: 2026-04-02 10:59:29.556387
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4d4b49b2b88'
down_revision: Union[str, None] = 'e2d213de7806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drives', sa.Column('auto_rip', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('drives', sa.Column('auto_rip_source_type', sa.Text(), nullable=False, server_default='unknown'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drives', 'auto_rip_source_type')
    op.drop_column('drives', 'auto_rip')
    # ### end Alembic commands ###
